version: '3.8'

services:
  db:
    image: postgres:14
    container_name: pg_beauty
    restart: always
    environment:
      POSTGRES_USER: manon
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: beauty_stats
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
